services:
  postgres:
    image: postgres:13
    container_name: redash_postgres
    environment:
      POSTGRES_USER: redash
      POSTGRES_PASSWORD: redash
      POSTGRES_DB: redash
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
    - redash_network

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: redash@redash.com
      PGADMIN_DEFAULT_PASSWORD: redash
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/root/.pgadmin
    ports:
      - "5050:80"
    networks:
      - redash_network
    restart: unless-stopped

  redis:
    image: redis:6.2
    container_name: redash_redis
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    networks:
      - redash_network

  redash_server:
    image: redash/redash:latest
    container_name: redash_server
    environment:
      REDASH_REDIS_URL: "redis://redis:6379/0"
      REDASH_DATABASE_URL: "postgresql://redash:redash@postgres:5432/redash"
      # REDASH_DATABASE_URL: "mongodb://mongo_user:mongo_password@redash_mongodb:27017/?authSource=mydatabase"

      REDASH_LOG_LEVEL: "INFO"
      REDASH_COOKIE_SECRET: "your_cookie_secret_here"
      REDASH_SECRET_KEY: "your_secret_key_here"
    depends_on:
      - postgres
      - redis
    ports:
      - "5002:5000"
    networks:
      - redash_network

  redash_worker:
    image: redash/redash:latest
    container_name: redash_worker
    environment:
      REDASH_REDIS_URL: "redis://redis:6379/0"
      REDASH_DATABASE_URL: "postgresql://redash:redash@postgres:5432/redash"
      # REDASH_DATABASE_URL: "mongodb://mongo_user:mongo_password@redash_mongodb:27017/?authSource=mydatabase"

      QUEUES: "celery"
      WORKERS_COUNT: 4
    depends_on:
      - postgres
      - redis
    networks:
      - redash_network

  mongodb:
      image: mongo:5.0
      container_name: redash_mongodb
      volumes:
        - mongodb_data:/data/db
        - ./mongo-init-scripts:/docker-entrypoint-initdb.d
      ports:
        - "27018:27017"
      environment:
        MONGO_INITDB_ROOT_USERNAME: mongo_user
        MONGO_INITDB_ROOT_PASSWORD: mongo_password
      networks:
        - redash_network

volumes:
  postgres_data:
  redis_data:
  pgadmin:
  mongodb_data:

networks:
  redash_network:
    driver: bridge

