version: '3'

services:
  redis:
    image: redis:6.2
    container_name: redash_redis
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"

  redash_server:
    image: redash/redash:latest
    container_name: redash_server
    environment:
      REDASH_REDIS_URL: "redis://redis:6379/0"
      REDASH_LOG_LEVEL: "INFO"
      REDASH_COOKIE_SECRET: "your-generated-secret-for-redash-secret-key"
      REDASH_SECRET_KEY: "your-generated-secret-for-redash-cookie-secret"
    depends_on:
      - redis
    ports:
      - "5001:5000"

  redash_worker:
    image: redash/redash:latest
    container_name: redash_worker
    environment:
      REDASH_REDIS_URL: "redis://redis:6379/0"
      QUEUES: "celery"
      WORKERS_COUNT: 4
    depends_on:
      - redis

volumes:
  redis_data:
